
const NAME = 'Account Management App';
export const APP_DETAILS = {
    NAME: NAME, NAME_FULL: NAME, APP_LOGO: "/logo/logo.png", APP_LOGO_ICO: "/logo/logo.ico",
}


export const DEFAULT_VARIABLES = {
    USER_PROFILE_PIC: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPfCfynXv42fOnrTQAs-99j09O8uz7mDilOQ&usqp=CAU",
}

export const SYSTEM_USERS = {
     MEMBER: 'MEMBER',
}

export const MAIN_COLORS = {
    DEEP: '#aae1fb', DEEPER: '', SIDEBAR: '#e9f0f4', DEEPEST: '#022f96'
}
export const ACCEPTED_FILE_TYPES = 'image/x-png, image/png, image/jpg, image/jpeg,image/jfif'


export const MESSAGES = {
    /// CRUD ALERTS FOR ALBUMS
    CREATE_ALBUM_SUCCESS: "successfully created album",
    CREATE_ALBUM_ERROR: "failed to create album",
    UPDATE_ALBUM_SUCCESS: "successfully updated album",
    UPDATE_ALBUM_ERROR: "failed to update album",
    DELETE_ALBUM_SUCCESS: "successfully deleted album",
   
    /// CRUD ALERTS FOR SONGS
    CREATE_SONG_SUCCESS: "successfully created song",
    CREATE_SONG_ERROR: "failed to create song",
    UPDATE_SONG_SUCCESS: "successfully updated song",
    UPDATE_SONG_ERROR: "failed to update song",
    DELETE_SONG_SUCCESS: "successfully deleted song",
    DELETE_SONG_ERROR: "failed to delete song",
    
    /// CRUD ALERTS FOR GENRES
    CREATE_GENRE_SUCCESS: "successfully created genre",
    CREATE_GENRE_ERROR: "failed to create genre",
    UPDATE_GENRE_SUCCESS: "successfully updated genre",
    UPDATE_GENRE_ERROR: "failed to update genre",
    DELETE_GENRE_SUCCESS: "successfully deleted genre",
}

export const KEYS = {
    LOCAL_STORAGE_TOKEN_KEY: "U2FsdGVkX1/UUUDSDJSDSDS/DSDSDSAYOUD+Kqx0bebEqAtQuEUU",
    PREV_LINK_LOCAL_STORAGE_KEY: "U2FsdGVkX1/wKy+DJlkadflkaEDJLDJS+sqe8pr64Dq2r"
}


export const NATIONALITY = [
    ["AFGHAN", "ALBANIAN", "ALGERIAN", "AMERICAN", "ANDORRAN", "ANGOLAN", "ANTIGUANS", "ARGENTINEAN", "ARMENIAN", "AUSTRALIAN", "AUSTRIAN", "AZERBAIJANI", "BAHAMIAN", "BAHRAINI", "BANGLADESHI", "BARBADIAN", "BARBUDANS", "BATSWANA", "BELARUSIAN", "BELGIAN", "BELIZEAN", "BENINESE", "BHUTANESE", "BOLIVIAN", "BOSNIAN", "BRAZILIAN", "BRITISH", "BRUNEIAN", "BULGARIAN", "BURKINABE", "BURMESE", "BURUNDIAN", "CAMBODIAN", "CAMEROONIAN", "CANADIAN", "CAPE VERDEAN", "CENTRAL_AFRICAN", "CHADIAN", "CHILEAN", "CHINESE", "COLOMBIAN", "COMORAN", "CONGOLESE", "COSTA_RICAN", "CROATIAN", "CUBAN", "CYPRIOT", "CZECH", "DANISH", "DJIBOUTI", "DOMINICAN", "DUTCH", "EAST_TIMORESE", "ECUADOREAN", "EGYPTIAN", "EMIRIAN", "EQUATORIAL_GUINEAN", "ERITREAN", "ESTONIAN", "ETHIOPIAN", "FIJIAN", "FILIPINO", "FINNISH", "FRENCH", "GABONESE", "GAMBIAN", "GEORGIAN", "GERMAN", "GHANAIAN", "GREEK", "GRENADIAN", "GUATEMALAN", "GUINEA_BISSAUAN", "GUINEAN", "GUYANESE", "HAITIAN", "HERZEGOVINIAN", "HONDURAN", "HUNGARIAN", "ICELANDER", "INDIAN", "INDONESIAN", "IRANIAN", "IRAQI", "IRISH", "ISRAELI", "ITALIAN", "IVORIAN", "JAMAICAN", "JAPANESE", "JORDANIAN", "KAZAKHSTANI", "KENYAN", "KITTIAN_AND_NEVISIAN", "KUWAITI", "KYRGYZ", "LAOTIAN", "LATVIAN", "LEBANESE", "LIBERIAN", "LIBYAN", "LIECHTENSTEINER", "LITHUANIAN", "LUXEMBOURGER", "MACEDONIAN", "MALAGASY", "MALAWIAN", "MALAYSIAN", "MALDIVAN", "MALIAN", "MALTESE", "MARSHALLESE", "MAURITANIAN", "MAURITIAN", "MEXICAN", "MICRONESIAN", "MOLDOVAN", "MONACAN", "MONGOLIAN", "MOROCCAN", "MOSOTHO", "MOTSWANA", "MOZAMBICAN", "NAMIBIAN", "NAURUAN", "NEPALESE", "NEW_ZEALANDER", "NI_VANUATU", "NICARAGUAN", "NIGERIEN", "NORTH_KOREAN", "NORTHERN_IRISH", "NORWEGIAN", "OMANI", "PAKISTANI", "PALAUAN", "PANAMANIAN", "PAPUA_NEW_GUINEAN", "PARAGUAYAN", "PERUVIAN", "POLISH", "PORTUGUESE", "QATARI", "ROMANIAN", "RUSSIAN", "RWANDAN", "SAINT_LUCIAN", "SALVADORAN", "SAMOAN", "SAN_MARINESE", "SAO_TOMEAN", "SAUDI", "SCOTTISH", "SENEGALESE", "SERBIAN", "SEYCHELLOIS", "SIERRA_LEONEAN", "SINGAPOREAN"]
]

export const GENDER = [
        "MALE", "FEMALE", "BOTH"
]

export const MERITAL_STATUS = [
    "SINGLE", "MARRIED", "DIVORCED", "WIDOWED"
]

export const USER_CATEGORY = {
    ADMIN: "ADMIN",
    CLIENT: "CLIENT",
}

export const VERIFICATION_STATUS = {
    UNVERIFIED: "UNVERIFIED",
    PENDING_VERIFICATION:"PENDING_VERIFICATION",
    VERIFIED: "VERIFIED"
}


export const VERIFICATION_REQUEST_STATUS = [
    "CONFIRMED", "REJECTED", "PENDING"
]
